version: "3.9"

services:
  # Front-end
  front:
    build: ./front # build from Dockerfile in ./front
    volumes:
      - ./shared_static:/app/build # mount static files so that we can provide them to nginx
    command: npm run build # build the front-end
    
  # Back-end
  back:
    build: ./back # build from Dockerfile in ./back
    
  # Proxy
  proxy:
    image: nginx:alpine
    volumes:
      - ./nginx/live.conf:/etc/nginx/conf.d/default.conf # Pass live config to nginx
      - ./shared_static:/etc/nginx/html # serve static files from nginx
    ports:
      - 80:80
    depends_on:
      - front