name: Backend Unit Tests CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build -t back back
      - name: Run the tests
        run: docker run back npm test