name: React Build CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build -t front front
      - name: Build the React app
        run: docker run -v $PWD/front/build:/app/build front npm run build
      - name: Export artifacts
        uses: actions/upload-artifact@v2
        with:
          name: react-build
          path: front/build